language: rust
rust: stable
dist: xenial

env:
  global:
    - RUST_BACKTRACE: full

os: linux

install:
  - rustup component add clippy
  - rustup component add rustfmt

before_script:
  - rustc -V
  - cargo -V
  - rustfmt --version
  - cargo clippy --version

script:
  - cargo clippy -- -D warnings
  - cargo fmt -- --check
  - cargo build
  - cargo test

notifications:
  email:
    on_success: never
    on_failure: change

# Caches $HOME/.cargo and $TRAVIS_BUILD_DIR/target.
cache: cargo
