language: rust
rust: stable
dist: xenial

env:
  global:
    - RUST_BACKTRACE: full

matrix:
  include:
    - os: osx
      env: LINT=false
    - os: linux
      env: LINT=true

install:
  - |
    if [[ "$LINT" == "true" ]]; then
        rustup component add clippy
        rustup component add rustfmt
    fi

before_script:
  - rustc -V
  - cargo -V
  - if [[ "$LINT" == "true" ]]; then rustfmt --version; fi
  - if [[ "$LINT" == "true" ]]; then cargo clippy --version; fi

script:
  - if [[ "$LINT" == "true" ]]; then cargo clippy -- -D warnings; fi
  - if [[ "$LINT" == "true" ]]; then cargo fmt -- --check; fi
  - cargo build
  - cargo test

notifications:
  email:
    on_success: never
    on_failure: change

# Caches $HOME/.cargo and $TRAVIS_BUILD_DIR/target.
cache: cargo
